board = """XXXX......
XXXX......
..XXX.....
..X.......
..........
..........
..........
..........
..........
.........."""

board = [[True if cell == "X" else False for cell in row] for row in board.split("\n")]

def count_sides(board, i, j):
    """
    https://www.imageprocessingplace.com/downloads_V3/root_downloads/tutorials/contour_tracing_Abeer_George_Ghuneim/square.html
    """
    print(board)
    boundary = [(i, j)]
    curr_pixel = (i, j)
    

count_sides(board, 0, 0)